apiVersion: v1
kind: Service
metadata:
  name: springboot-container-lb
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: springboot-container